CREATE TABLE [dbo].[Role]
(
	[Id] INT UNIQUE IDENTITY(1,1) NOT NULL,
	[Label] VARCHAR(250) NOT NULL,
	[CreatedAt] DATETIME NOT NULL,
	[UpdatedAt] DATETIME NULL,
	[IsActive] BIT NOT NULL DEFAULT(1),
	CONSTRAINT [PK_Role] PRIMARY KEY(Id),
)
