CREATE TABLE [dbo].[User]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Email] NVARCHAR(300) NOT NULL,
	[Firstname] NVARCHAR(150) NOT NULL,
	[Lastname] NVARCHAR(200) NOT NULL,
	[Password] NVARCHAR(200) NOT NULL,
	[Old] INT NOT NULL,
	[Image] VARBINARY(MAX) NULL,
	CONSTRAINT [PK_USER] PRIMARY KEY(Id),
	CONSTRAINT [UNIQUE_USER] UNIQUE(Id),
	CONSTRAINT [UNIQUE_EMAIL] UNIQUE(Email),
	CONSTRAINT [CHECK_EMAIL] CHECK (DATALENGTH(Email) <= 300),
	CONSTRAINT [CHECK_FIRSTNAME] CHECK (DATALENGTH(Email) <= 150),
	CONSTRAINT [CHECK_LASTNAME] CHECK (DATALENGTH(Email) <= 200),
	CONSTRAINT [CHECK_PASSWORD] CHECK (DATALENGTH(Email) <= 200)
)
